CREATE DATABASE IF NOT EXISTS test;

# user
DROP TABLE IF EXISTS test.user;
CREATE TABLE test.user (
  id       INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255),
  password VARCHAR(255)
);

TRUNCATE TABLE test.user;

SELECT *
FROM test.user;